# etl-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: etl-job
  labels:
    app: etl-job
spec:
  # Job will retry up to 3 times on failure
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: etl-job
    spec:
      containers:
      - name: etl
        image: image-registry.openshift-image-registry.svc:5000/ds551-2025fall-cb9303/elt-app:latest
        # image: quay.io/tigeryi/etl-app:latest
        imagePullPolicy: Always
        env:
          - name: POSTGRES_HOST
            value: "postgres"  # This should match the service name defined in postgres-service.yaml
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "mydb"
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            value: "password"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/data"
          name: etl-data
      volumes:
      - name: etl-data
        persistentVolumeClaim:
          claimName: etl-pvc
      restartPolicy: Never